name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Executa o fluxo de trabalho quando há push na branch 'main'
  pull_request:
    branches:
      - main  # Executa o fluxo de trabalho quando há pull request para a branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Define o sistema operacional da máquina onde a ação será executada

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Configura o ambiente Node.js
        with:
          node-version: '14'  # Define a versão do Node.js

      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run tests
        run: npm test  # Executa os testes do projeto
